/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uasd.insurance.vistas.transacciones;

import com.itla.insurance.dao.AfiliadoDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Sulenni
 */
public class frm_Pago extends javax.swing.JInternalFrame {

    AfiliadoDao afiliadoDao;

    /**
     * Creates new form frm_Pago
     */
    public frm_Pago() throws Exception {
        initComponents();
        jtxtReclamacionesPendientes.setText("");
        jtxtReclamacionesPagas.setText("");
        afiliadoDao = new AfiliadoDao();
        btnMarcarPago.setEnabled(false);
        RefrescarTablas();
    }
    
    private void RefrescarTablas() throws SQLException {
        RefrescarTablaPendientes();
        RefrescarTablapagas();
    }
    
    private void RefrescarTablaPendientes() throws SQLException{
        jtblReclamacionesPendientes.setModel(afiliadoDao.getModelReclamacion(afiliadoDao.GetAllReclamacion(false, jtxtReclamacionesPendientes.getText())));
        RedisenarTablaReclamacionesPendientes();
    }
    
    private void RefrescarTablapagas() throws SQLException{
        jtblReclamacionesPagas.setModel(afiliadoDao.getModelReclamacion(afiliadoDao.GetAllReclamacion(true, jtxtReclamacionesPagas.getText())));
        RedisenarTablaReclamacionesPagas();
    }
    
    private void RedisenarTablaReclamacionesPendientes(){
        jtblReclamacionesPendientes.removeColumn(jtblReclamacionesPendientes.getColumnModel().getColumn(5));
        jtblReclamacionesPendientes.removeColumn(jtblReclamacionesPendientes.getColumnModel().getColumn(4));
        jtblReclamacionesPendientes.removeColumn(jtblReclamacionesPendientes.getColumnModel().getColumn(2));
        jtblReclamacionesPendientes.removeColumn(jtblReclamacionesPendientes.getColumnModel().getColumn(0));
    }
    
    
    private void RedisenarTablaReclamacionesPagas(){
        jtblReclamacionesPagas.removeColumn(jtblReclamacionesPagas.getColumnModel().getColumn(6));
        jtblReclamacionesPagas.removeColumn(jtblReclamacionesPagas.getColumnModel().getColumn(5));
        jtblReclamacionesPagas.removeColumn(jtblReclamacionesPagas.getColumnModel().getColumn(4));
        jtblReclamacionesPagas.removeColumn(jtblReclamacionesPagas.getColumnModel().getColumn(2));
        jtblReclamacionesPagas.removeColumn(jtblReclamacionesPagas.getColumnModel().getColumn(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblReclamacionesPendientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxtReclamacionesPendientes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblReclamacionesPagas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtReclamacionesPagas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnMarcarPago = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtblReclamacionesPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Afiliado", "Prestador", "Total a Pagar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtblReclamacionesPendientes.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jtblReclamacionesPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtblReclamacionesPendientesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtblReclamacionesPendientes);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/doctor (2).png"))); // NOI18N
        jLabel1.setText("Reclamaciones Pendientes de Pago");

        jtxtReclamacionesPendientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtReclamacionesPendientesKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/magnifying-glass.png"))); // NOI18N
        jLabel6.setText("Consultas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtReclamacionesPendientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtReclamacionesPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtblReclamacionesPagas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Afiliado", "Prestador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtblReclamacionesPagas.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(jtblReclamacionesPagas);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/doctor (2).png"))); // NOI18N
        jLabel2.setText("Reclamaciones Pagas");

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/magnifying-glass.png"))); // NOI18N
        jLabel5.setText("Consultas");

        jtxtReclamacionesPagas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtReclamacionesPagasKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtxtReclamacionesPagas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtReclamacionesPagas, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(322, 67));

        btnMarcarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/confirm.png"))); // NOI18N
        btnMarcarPago.setText("Marcar Pago");
        btnMarcarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarPagoActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMarcarPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarcarPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jtblReclamacionesPendientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblReclamacionesPendientesMouseReleased

        ListSelectionModel selectionModel = jtblReclamacionesPendientes.getSelectionModel();
        if(selectionModel.isSelectionEmpty()) {
            btnMarcarPago.setEnabled(false);
            return;
        }
        btnMarcarPago.setEnabled(true);
    }//GEN-LAST:event_jtblReclamacionesPendientesMouseReleased

    private void btnMarcarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarPagoActionPerformed
        ListSelectionModel selectionModel = jtblReclamacionesPendientes.getSelectionModel();
        if(selectionModel.isSelectionEmpty()) {
            return;
        }
        int[] selectedRows = jtblReclamacionesPendientes.getSelectedRows();
        jtblReclamacionesPendientes.setEnabled(false);
        for (int selectedRow : selectedRows) {
            try{
                afiliadoDao.setReclamacionPaidStatus((int) jtblReclamacionesPendientes.getModel().getValueAt(selectedRow, 0), true);
            } catch(Exception e){
                Logger.getLogger(frm_Pago.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        try{
            btnMarcarPago.setEnabled(false);
            RefrescarTablas();
        }catch(Exception e){
                Logger.getLogger(frm_Pago.class.getName()).log(Level.SEVERE, null, e);
        }
        jtblReclamacionesPendientes.setEnabled(true);
    }//GEN-LAST:event_btnMarcarPagoActionPerformed

    private void jtxtReclamacionesPagasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtReclamacionesPagasKeyTyped
        try {
            RefrescarTablapagas();
        } catch (SQLException ex) {
            Logger.getLogger(frm_Pago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtxtReclamacionesPagasKeyTyped

    private void jtxtReclamacionesPendientesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtReclamacionesPendientesKeyTyped
        try {
            RefrescarTablaPendientes();
        } catch (SQLException ex) {
            Logger.getLogger(frm_Pago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtxtReclamacionesPendientesKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarcarPago;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtblReclamacionesPagas;
    private javax.swing.JTable jtblReclamacionesPendientes;
    private javax.swing.JTextField jtxtReclamacionesPagas;
    private javax.swing.JTextField jtxtReclamacionesPendientes;
    // End of variables declaration//GEN-END:variables
}
