/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uasd.insurance.vistas.transacciones;

import com.itla.insurance.dao.AfiliadoDao;
import com.itla.insurance.dto.AfiliadoDto;
import com.itla.insurance.dto.EstudioDto;
import com.itla.insurance.dto.PrestadoresDto;
import com.itla.insurance.dto.ReclamacionDto;
import com.itla.insurance.dto.ServicioDto;
import com.itla.insurance.dto.Tipo_CoberturaDto;
import com.uasd.insurance.vistas.mantenimientos.frm_Afiliado;
import com.uasd.insurance.vistas.mantenimientos.frm_BuscarAfiliado;
import com.uasd.insurance.vistas.mantenimientos.frm_BuscarPrestador;
import com.uasd.insurance.vistas.principal.frm_Principal;
import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sulenni
 */
public class frm_Reclamacion extends javax.swing.JInternalFrame {

    AfiliadoDto afiliadoDto;
    AfiliadoDao afiliadoDao;
    EstudioDto estudioDto;
    PrestadoresDto prestadorDto;
    List<ServicioDto> servicios;
    frm_Principal principal;
    
    public frm_Reclamacion() throws Exception {
        initComponents();
        afiliadoDao = new AfiliadoDao();
        //afiliadoDto = new AfiliadoDto();
        jlblNoReclamacion.setText(afiliadoDao.GenerarContrato());
        
        jtblListaEstudio.setModel(afiliadoDao.getModelEstudio(afiliadoDao.GetAllEstudio()));
        RedisenarTablaEstudio();
        RedisenarTablaServicio();
    }
    
    public frm_Reclamacion(frm_Principal principal) throws Exception {
        initComponents();
        afiliadoDao = new AfiliadoDao();
        //afiliadoDto = new AfiliadoDto();
        estudioDto = new EstudioDto();
        servicios = new ArrayList<ServicioDto>();
        this.principal = principal;
        
//        jlblNoReclamacion.setText(afiliadoDao.GenerarContrato());
        
        jtblServicio.setModel(afiliadoDao.getModelEstudioSeleccionado());
//        jtblListaEstudio.setModel(afiliadoDao.getModelEstudio(afiliadoDao.GetAllEstudio()));
        
        RedisenarTablaEstudio();
        RedisenarTablaServicio();
        jTable1.setModel(afiliadoDao.getModelReclamacion(afiliadoDao.GetAllReclamacion()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlReclamacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblServicio = new javax.swing.JTable();
        jlblReclamacion = new javax.swing.JLabel();
        jlblNoReclamacion = new javax.swing.JLabel();
        jlblPoliza = new javax.swing.JLabel();
        jtxtNoPoliza = new javax.swing.JTextField();
        jtxtNombreAfiliado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtIdPrestador = new javax.swing.JTextField();
        jtxtNombrePrestador = new javax.swing.JTextField();
        jbttAfiliado = new javax.swing.JButton();
        jbttPrestador = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblListaEstudio = new javax.swing.JTable();
        jtxtBuscaEstudio = new javax.swing.JTextField();
        jbttBuscaEstudio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbttBuscaEstudio1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jbttImprimir = new javax.swing.JButton();
        jbttNuevo = new javax.swing.JButton();
        jbttGuardar = new javax.swing.JButton();
        jbttSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));

        jpnlReclamacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel1.setText("FORMULARIO RECLAMACION");

        jtblServicio.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jtblServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblServicio);

        jlblReclamacion.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jlblReclamacion.setText("No. Reclamación");

        jlblNoReclamacion.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jlblNoReclamacion.setForeground(new java.awt.Color(153, 0, 0));
        jlblNoReclamacion.setText("0");

        jlblPoliza.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jlblPoliza.setText("No. Póliza");

        jtxtNoPoliza.setEditable(false);
        jtxtNoPoliza.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N

        jtxtNombreAfiliado.setEditable(false);
        jtxtNombreAfiliado.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jtxtNombreAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreAfiliadoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel2.setText("Prestador");

        jtxtIdPrestador.setEditable(false);
        jtxtIdPrestador.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N

        jtxtNombrePrestador.setEditable(false);
        jtxtNombrePrestador.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jtxtNombrePrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombrePrestadorActionPerformed(evt);
            }
        });

        jbttAfiliado.setText("...");
        jbttAfiliado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbttAfiliadoMousePressed(evt);
            }
        });
        jbttAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttAfiliadoActionPerformed(evt);
            }
        });

        jbttPrestador.setText("...");
        jbttPrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttPrestadorActionPerformed(evt);
            }
        });

        jtblListaEstudio.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jtblListaEstudio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblListaEstudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtblListaEstudioMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtblListaEstudio);

        jtxtBuscaEstudio.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jtxtBuscaEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBuscaEstudioActionPerformed(evt);
            }
        });
        jtxtBuscaEstudio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBuscaEstudioKeyTyped(evt);
            }
        });

        jbttBuscaEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttBuscaEstudioActionPerformed(evt);
            }
        });

        jbttBuscaEstudio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttBuscaEstudio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlReclamacionLayout = new javax.swing.GroupLayout(jpnlReclamacion);
        jpnlReclamacion.setLayout(jpnlReclamacionLayout);
        jpnlReclamacionLayout.setHorizontalGroup(
            jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlReclamacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlReclamacionLayout.createSequentialGroup()
                        .addComponent(jlblReclamacion)
                        .addGap(22, 22, 22)
                        .addComponent(jlblNoReclamacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(353, 353, 353))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlReclamacionLayout.createSequentialGroup()
                        .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblPoliza, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtNoPoliza, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jtxtIdPrestador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNombreAfiliado)
                            .addComponent(jtxtNombrePrestador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbttPrestador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttAfiliado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jpnlReclamacionLayout.createSequentialGroup()
                        .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlReclamacionLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtBuscaEstudio, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbttBuscaEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttBuscaEstudio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlReclamacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jpnlReclamacionLayout.setVerticalGroup(
            jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlReclamacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblReclamacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblNoReclamacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlReclamacionLayout.createSequentialGroup()
                        .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxtNombreAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbttAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxtNoPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtNombrePrestador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtIdPrestador)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbttPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnlReclamacionLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlblPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlReclamacionLayout.createSequentialGroup()
                        .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbttBuscaEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttBuscaEstudio1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnlReclamacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtBuscaEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbttImprimir.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jbttImprimir.setText("Imprimir");
        jbttImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttImprimirActionPerformed(evt);
            }
        });

        jbttNuevo.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jbttNuevo.setText("Nuevo");
        jbttNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttNuevoActionPerformed(evt);
            }
        });

        jbttGuardar.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jbttGuardar.setText("Guardar");
        jbttGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttGuardarActionPerformed(evt);
            }
        });

        jbttSalir.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jbttSalir.setText("Salir");
        jbttSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbttImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbttNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbttGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbttSalir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbttGuardar)
                    .addComponent(jbttSalir)
                    .addComponent(jbttNuevo)
                    .addComponent(jbttImprimir))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel4.setText("Consultas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnlReclamacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnlReclamacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbttImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttImprimirActionPerformed

    }//GEN-LAST:event_jbttImprimirActionPerformed

    private void jbttNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttNuevoActionPerformed

        habilitarCampos(true);
        try {
            jlblNoReclamacion.setText(afiliadoDao.GenerarContrato());
        } catch (SQLException ex) {
            Logger.getLogger(frm_Reclamacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        afiliadoDto = null;
        prestadorDto = null;
           
        DefaultTableModel dtm = ((DefaultTableModel)jtblServicio.getModel());
        int rowCount  = dtm.getRowCount();
        
        for (int i = rowCount-1; i>=0; i--) {
            dtm.removeRow(i);
        }
        jtxtNombrePrestador.setText("");
        jtxtIdPrestador.setText("");
        jtxtNoPoliza.setText("");
        jtxtNombreAfiliado.setText("");
    }//GEN-LAST:event_jbttNuevoActionPerformed

    private void jbttGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttGuardarActionPerformed
        List<ServicioDto> serviciosEstudios = new ArrayList<ServicioDto>();
        ReclamacionDto reclamacionEstudio;
        ServicioDto servicioEstudio;
        int i;
        reclamacionEstudio = new ReclamacionDto();
        reclamacionEstudio.setId(Integer.parseInt(jlblNoReclamacion.getText()));
        reclamacionEstudio.setId_afiliado(afiliadoDto.getId());
        reclamacionEstudio.setId_prestador(prestadorDto.getId());
        afiliadoDao.insertReclamacion(reclamacionEstudio);
        
        for(i=0; i<jtblServicio.getRowCount(); i++){
           servicioEstudio = new ServicioDto();
           servicioEstudio.setId_servicio((int) jtblServicio.getModel().getValueAt(i, 1));
           servicioEstudio.setCodigo(jlblNoReclamacion.getText());
           servicioEstudio.setMonto_reclamado((Float) jtblServicio.getModel().getValueAt(i, 2));
           servicioEstudio.setMonto_doferencia((Float) jtblServicio.getModel().getValueAt(i, 3));
           servicioEstudio.setMonto_pagar((Float) jtblServicio.getModel().getValueAt(i, 4));
           servicioEstudio.setNo_reclamacion(Integer.parseInt(jlblNoReclamacion.getText()));
           servicioEstudio.setNo_autorizacion(Integer.parseInt(jlblNoReclamacion.getText()));
           servicioEstudio.setMonto_total((Float) jtblServicio.getModel().getValueAt(i, 2));
           

            //apagar
           serviciosEstudios.add(servicioEstudio);
           
           //codigo para guardar
        }
        afiliadoDao.insertListServicio(serviciosEstudios);
        
        try {
            jTable1.setModel(afiliadoDao.getModelReclamacion(afiliadoDao.GetAllReclamacion()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_Reclamacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbttGuardarActionPerformed

    private void jbttSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbttSalirActionPerformed

    private void jbttBuscaEstudio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttBuscaEstudio1ActionPerformed
        quitarEstudio((Integer) jtblServicio.getModel().getValueAt(jtblServicio.getSelectedRow(), 1));
    }//GEN-LAST:event_jbttBuscaEstudio1ActionPerformed

    private void jbttBuscaEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttBuscaEstudioActionPerformed

        if(afiliadoDto==null){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un afiliado para continuar.", "Afiliado no seleccionado", JOptionPane.ERROR_MESSAGE);
            jbttAfiliado.setSelected(true);
        }else
        if(prestadorDto==null){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un prestador para continuar.", "Prestador no seleccionado", JOptionPane.ERROR_MESSAGE);
            jbttPrestador.setSelected(true);
        }else{
            try {
                this.asignarEstudio(estudioDto);
            } catch (Exception ex) {
                Logger.getLogger(frm_Reclamacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jbttBuscaEstudioActionPerformed

    private void jtxtBuscaEstudioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscaEstudioKeyTyped
        try {
            jtblListaEstudio.setModel(afiliadoDao.filtraModelEstudio(jtxtBuscaEstudio.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_Reclamacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        jtblListaEstudio.setTableHeader(null);
        jtblListaEstudio.removeColumn(jtblListaEstudio.getColumnModel().getColumn(1));
        jtblListaEstudio.removeColumn(jtblListaEstudio.getColumnModel().getColumn(1));
    }//GEN-LAST:event_jtxtBuscaEstudioKeyTyped

    private void jtxtBuscaEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBuscaEstudioActionPerformed

    }//GEN-LAST:event_jtxtBuscaEstudioActionPerformed

    private void jtblListaEstudioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblListaEstudioMousePressed
        estudioDto.setNombre((String) (jtblListaEstudio.getModel().getValueAt(jtblListaEstudio.getSelectedRow(), 0)));
        estudioDto.setId((int) (jtblListaEstudio.getModel().getValueAt(jtblListaEstudio.getSelectedRow(), 1)));
        estudioDto.setPrecio((Float) (jtblListaEstudio.getModel().getValueAt(jtblListaEstudio.getSelectedRow(), 2)));
    }//GEN-LAST:event_jtblListaEstudioMousePressed

    private void jbttPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttPrestadorActionPerformed
        frm_BuscarPrestador buscarPrestador = null;
        try {
            buscarPrestador = new frm_BuscarPrestador(this);

        } catch (Exception ex) {
            Logger.getLogger(frm_Reclamacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        principal.agregarFormulario(buscarPrestador);
    }//GEN-LAST:event_jbttPrestadorActionPerformed

    private void jbttAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttAfiliadoActionPerformed
        frm_BuscarAfiliado buscarAfiliado = null;
        try {
            buscarAfiliado = new frm_BuscarAfiliado(this);

        } catch (Exception ex) {
            Logger.getLogger(frm_Reclamacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        principal.agregarFormulario(buscarAfiliado);

    }//GEN-LAST:event_jbttAfiliadoActionPerformed

    private void jbttAfiliadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbttAfiliadoMousePressed

    }//GEN-LAST:event_jbttAfiliadoMousePressed

    private void jtxtNombrePrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombrePrestadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombrePrestadorActionPerformed

    private void jtxtNombreAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreAfiliadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreAfiliadoActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        habilitarCampos(false);
        try {
            afiliadoDto = afiliadoDao.GetAfiliadoById((int) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3));
            prestadorDto = afiliadoDao.GetPrestadorById((int) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4));
            servicios = afiliadoDao.GetAllEstudiosByReclamacion((int) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0));
        } catch (SQLException ex) {
            Logger.getLogger(frm_Reclamacion.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        jlblNoReclamacion.setText(Integer.toString(servicios.get(0).getNo_reclamacion()));
        showAfiliado(afiliadoDto);
        showPrestador(prestadorDto);
        showServicios(servicios);
    }//GEN-LAST:event_jTable1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbttAfiliado;
    private javax.swing.JButton jbttBuscaEstudio;
    private javax.swing.JButton jbttBuscaEstudio1;
    private javax.swing.JButton jbttGuardar;
    private javax.swing.JButton jbttImprimir;
    private javax.swing.JButton jbttNuevo;
    private javax.swing.JButton jbttPrestador;
    private javax.swing.JButton jbttSalir;
    private javax.swing.JLabel jlblNoReclamacion;
    private javax.swing.JLabel jlblPoliza;
    private javax.swing.JLabel jlblReclamacion;
    private javax.swing.JPanel jpnlReclamacion;
    private javax.swing.JTable jtblListaEstudio;
    private javax.swing.JTable jtblServicio;
    private javax.swing.JTextField jtxtBuscaEstudio;
    private javax.swing.JTextField jtxtIdPrestador;
    private javax.swing.JTextField jtxtNoPoliza;
    private javax.swing.JTextField jtxtNombreAfiliado;
    private javax.swing.JTextField jtxtNombrePrestador;
    // End of variables declaration//GEN-END:variables

    public void showAfiliado(AfiliadoDto afiliadoDto) {
        this.afiliadoDto=afiliadoDto;
        jtxtNoPoliza.setText(Integer.toString(afiliadoDto.getNo_Poliza()));
        jtxtNombreAfiliado.setText(afiliadoDto.getNombre());
    }
    
    public void showPrestador(PrestadoresDto prestadorDto) {
        jtxtIdPrestador.setText(prestadorDto.getCodigo());
        jtxtNombrePrestador.setText(prestadorDto.getNombre());
        this.prestadorDto=prestadorDto;
        
        try {
            //Llenar tabla de analisis que ofrece ese prestador
            jtblListaEstudio.setModel(afiliadoDao.getModelAnalisis(afiliadoDao.GetAllAnalisisByPrestador(prestadorDto.getId())));
        } catch (SQLException ex) {
            Logger.getLogger(frm_Reclamacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void RedisenarTablaEstudio() {
        //jtblListaEstudio.setTableHeader(null);
        jtblListaEstudio.removeColumn(jtblListaEstudio.getColumnModel().getColumn(1));
        jtblListaEstudio.removeColumn(jtblListaEstudio.getColumnModel().getColumn(1));
    }
    
    private void RedisenarTablaServicio(){
        jtblServicio.removeColumn(jtblServicio.getColumnModel().getColumn(1));
    }

    private void quitarEstudio(Integer  idServicio){
        
        for (int i = 0; i < jtblServicio.getRowCount(); i++) { 
            if(idServicio==jtblServicio.getModel().getValueAt(i, 1)){
                ((DefaultTableModel)jtblServicio.getModel()).removeRow(i);
            }
        }
//        revalidate();
    }
    private void asignarEstudio(EstudioDto estudioDto) throws Exception {
 
        this.afiliadoDto.getIdTipoCobertura();
        Object[] registro = new Object[5];
        
        registro[0] = estudioDto.getNombre();
        registro[1] = estudioDto.getId();
        registro[2] = estudioDto.getPrecio();
        int porciento;
        float diferencia;
        float apagar;
        
        Tipo_CoberturaDto cober;
        
        cober = afiliadoDao.cobertura(this.afiliadoDto.getIdTipoCobertura());
        porciento = cober.getPorciento(); 
        
        diferencia = ((porciento*estudioDto.getPrecio())/100);
        apagar = estudioDto.getPrecio()-diferencia;
                
        registro[3] = diferencia;
        int idSeleccion = estudioDto.getId();
        boolean b=true;
        
        registro[4] = apagar;
        //recorre tabla servicios
        for (int i = 1; i <= jtblServicio.getRowCount(); i++) { 
            
            //Si el rowcount de la tabla servicio esta vacia no hace nada. no se pasa.
            if (jtblServicio.getRowCount()==0) {
                ((DefaultTableModel) jtblServicio.getModel()).addRow(registro);
            }
            else { //si el rowcount es diferente a cero agrega el estudio a la tabla servicio
                try {
                    int cell = (int)jtblServicio.getModel().getValueAt(i-1, 1);
                    if (idSeleccion==cell) {
                        b=false;      
                    }
                } catch (Exception e) {
                }
                
            }
        }
        
        if(b){
          ((DefaultTableModel) jtblServicio.getModel()).addRow(registro);
        }else{
            JOptionPane.showMessageDialog(null, "Este estudio ya ha sido asignado.", "", JOptionPane.ERROR_MESSAGE);
            
        }
        
    }    

    private void showServicios(List<ServicioDto> servicios) {
        EstudioDto estudio;
        DefaultTableModel dtm = ((DefaultTableModel)jtblServicio.getModel());
        int rowCount  = dtm.getRowCount();
        
        for (int i = rowCount-1; i>=0; i--) {
            dtm.removeRow(i);
        }
        for (ServicioDto servicio : servicios) {
            
            
            try {
                estudio = afiliadoDao.GetEstudioById(servicio.getId_servicio());
                asignarEstudio(estudio);
            } catch (Exception ex) {
                Logger.getLogger(frm_Reclamacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }

    private void habilitarCampos(boolean b) {
        jbttBuscaEstudio.setEnabled(b);
        jbttBuscaEstudio1.setEnabled(b);
        jbttAfiliado.setEnabled(b);
        jbttPrestador.setEnabled(b);
        jbttGuardar.setEnabled(b);
        jtxtBuscaEstudio.setEnabled(b);
    }
}
