/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uasd.insurance.vistas.mantenimientos;

import com.itla.insurance.dao.AfiliadoDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Giame
 */
public class frm_BuscarServicio extends javax.swing.JInternalFrame {

    frm_Prestadores frmPrestadores;
    AfiliadoDao afiliadoDao;
    /**
     * Creates new form frm_BuscarServicio
     */
    public frm_BuscarServicio() {
        initComponents();
        try {
            afiliadoDao = new AfiliadoDao();
        } catch (Exception ex) {
            Logger.getLogger(frm_BuscarServicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        LlenarAnalisis();
    }
    public frm_BuscarServicio(frm_Prestadores frm) {
        initComponents();
        frmPrestadores = frm;
        try {
            afiliadoDao = new AfiliadoDao();
        } catch (Exception ex) {
            Logger.getLogger(frm_BuscarServicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        LlenarAnalisis();
    }

    private void LlenarAnalisis(){
        try {
            
            jtblServicios.setModel(afiliadoDao.getModelAnalisis(afiliadoDao.GetAllAnalisis()));
            
        } catch (SQLException ex) {
            
            Logger.getLogger(frm_Prestadores.class.getName()).log(Level.SEVERE, null, ex);
        }
        RedisenarTablaServicios();
    }
    private void RedisenarTablaServicios(){
        jtblServicios.removeColumn(jtblServicios.getColumnModel().getColumn(1));
        jtblServicios.removeColumn(jtblServicios.getColumnModel().getColumn(1));

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jtblServicios = new javax.swing.JTable();
        txtBusqueda = new javax.swing.JTextField();
        jlblNombre6 = new javax.swing.JLabel();
        jtxtPrecio = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setClosable(true);

        jtblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane3.setViewportView(jtblServicios);

        jlblNombre6.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jlblNombre6.setText("Precio");

        jtxtPrecio.setMinimumSize(new java.awt.Dimension(55, 28));

        jButton3.setText(" Agregar servicio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlblNombre6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtBusqueda)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNombre6)
                    .addComponent(jtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlblNombre6;
    private javax.swing.JTable jtblServicios;
    private javax.swing.JTextField jtxtPrecio;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
