/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uasd.insurance.vistas.mantenimientos;

/**
 *
 * @author Sulenni
 */
public class frm_Especialidad extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_Especialidad
     */
    public frm_Especialidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlEspecialidad = new javax.swing.JPanel();
        jlblEspecialidad = new javax.swing.JLabel();

        jlblEspecialidad.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jlblEspecialidad.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sulenni\\Downloads\\microscope.png")); // NOI18N
        jlblEspecialidad.setText("FORMULARIO ESPECIALIDAD");

        javax.swing.GroupLayout jpnlEspecialidadLayout = new javax.swing.GroupLayout(jpnlEspecialidad);
        jpnlEspecialidad.setLayout(jpnlEspecialidadLayout);
        jpnlEspecialidadLayout.setHorizontalGroup(
            jpnlEspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlEspecialidadLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jlblEspecialidad)
                .addContainerGap())
        );
        jpnlEspecialidadLayout.setVerticalGroup(
            jpnlEspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlEspecialidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblEspecialidad)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblEspecialidad;
    private javax.swing.JPanel jpnlEspecialidad;
    // End of variables declaration//GEN-END:variables
}
