/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uasd.insurance.vistas.mantenimientos;

import com.itla.insurance.dto.AfiliadoDto;
import com.itla.insurance.dao.AfiliadoDao;
import com.uasd.insurance.vistas.transacciones.frm_Reclamacion;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sulenni
 */
public class frm_BuscarAfiliado extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_BuscarAfiliado
     */
    AfiliadoDao afiliadoDao;
    AfiliadoDto afiliadoDto;
    frm_Reclamacion reclamacion;
    
    public frm_BuscarAfiliado() throws Exception {
        initComponents();
        afiliadoDao = new AfiliadoDao();
        afiliadoDto = new AfiliadoDto();
    }
    
    public frm_BuscarAfiliado(frm_Reclamacion reclamacion) throws Exception {
        initComponents();
        afiliadoDao = new AfiliadoDao();
        afiliadoDto = new AfiliadoDto();
        
        try {
            jtblAfiliado.setModel(afiliadoDao.getModelAfiliado(afiliadoDao.GetAllAfiliado()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_BuscarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
        }

        RedisenarTablaAfiliado();

        this.reclamacion = reclamacion;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblAfiliado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtblAfiliado.setAutoCreateRowSorter(true);
        jtblAfiliado.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jtblAfiliado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtblAfiliado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtblAfiliadoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtblAfiliado);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sulenni\\Downloads\\search.png")); // NOI18N

        jtxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBuscarActionPerformed(evt);
            }
        });
        jtxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBuscarKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sulenni\\Downloads\\next-page.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 3, 18)); // NOI18N
        jLabel2.setText("CONSULTA DE AFILIADOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblAfiliadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblAfiliadoMousePressed
        jtblAfiliado.setSelectionBackground(Color.BLUE);
        jtblAfiliado.setSelectionForeground(Color.white);
        
        afiliadoDto.setId((int) jtblAfiliado.getModel().getValueAt(jtblAfiliado.getSelectedRow(), 4));
        afiliadoDto.setNo_Poliza((int) jtblAfiliado.getModel().getValueAt(jtblAfiliado.getSelectedRow(), 0));
        afiliadoDto.setNombre((java.lang.String) (jtblAfiliado.getModel().getValueAt(jtblAfiliado.getSelectedRow(), 2)));
        afiliadoDto.setIdTipoCobertura((int) jtblAfiliado.getModel().getValueAt(jtblAfiliado.getSelectedRow(), 16));
    }//GEN-LAST:event_jtblAfiliadoMousePressed

    private void jtxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBuscarActionPerformed

    private void jtxtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarKeyTyped
        try {
            jtblAfiliado.setModel(afiliadoDao.filtraModelAfiliado(jtxtBuscar.getText()));
            
            //RedisenarTablaAfiliado();
        } catch (SQLException ex) {
            Logger.getLogger(frm_BuscarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
        }
//        RedisenarTablaAfiliado();
        jtblAfiliado.setTableHeader(null);
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        
    }//GEN-LAST:event_jtxtBuscarKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.reclamacion.showAfiliado(afiliadoDto);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblAfiliado;
    private javax.swing.JTextField jtxtBuscar;
    // End of variables declaration//GEN-END:variables

    private void RedisenarTablaAfiliado() {
       // jtblAfiliado.setTableHeader(null);
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
        jtblAfiliado.removeColumn(jtblAfiliado.getColumnModel().getColumn(4));
    }
}
