/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uasd.insurance.vistas.principal;

import com.itla.insurance.dao.UserDao;
import com.itla.insurance.dto.UserDto;
import com.uasd.insurance.vistas.mantenimientos.frm_Afiliado;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Painter;
import javax.swing.UIManager;
import javax.swing.WindowConstants;

/**
 *
 * @author Sulenni
 */
public class frm_Login extends javax.swing.JFrame {

    /**
     * Creates new form frm_Login
     */
    public frm_Login() {
        UIManager.put("InternalFrame[Enabled+WindowFocused].backgroundPainter", new Painter<Object>() {
        @Override
	public void paint(Graphics2D g, Object c, int w, int h) {
                g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g.setStroke(new BasicStroke(2f));
                g.setColor(new Color(81,92,107));
                g.fillRoundRect(0, 0, w-1, h-1, 8, 8);
                g.setColor(new Color(35,70,70));
                g.drawRoundRect(0, 0, w-1, h-1, 8, 8);
	}
    });
		
	UIManager.put("InternalFrame[Enabled].backgroundPainter", new Painter<Object>() {

            @Override
            public void paint(Graphics2D g, Object c, int w, int h) {
		g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g.setStroke(new BasicStroke(2f));
                g.setColor(new Color(81,92,107));
                g.fillRoundRect(0, 0, w-1, h-1, 8, 8);
                g.setColor(new Color(81,92,107));
                g.drawRoundRect(0, 0, w-1, h-1, 8, 8);
            }
        });
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblUsuario = new javax.swing.JLabel();
        jlblPassqord = new javax.swing.JLabel();
        jtxtUser = new javax.swing.JTextField();
        jbttEntrar = new javax.swing.JButton();
        jlblEntradaUsuario = new javax.swing.JLabel();
        jbttSalir = new javax.swing.JButton();
        jtxtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblUsuario.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jlblUsuario.setText("Usuario");

        jlblPassqord.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jlblPassqord.setText("Password");

        jtxtUser.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jtxtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtUserKeyReleased(evt);
            }
        });

        jbttEntrar.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jbttEntrar.setText("Entrar");
        jbttEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttEntrarActionPerformed(evt);
            }
        });

        jlblEntradaUsuario.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jlblEntradaUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sulenni\\Downloads\\padlock (1).png")); // NOI18N
        jlblEntradaUsuario.setText("Entrada de Usuario");

        jbttSalir.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jbttSalir.setText("Salir");
        jbttSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttSalirActionPerformed(evt);
            }
        });

        jtxtPass.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jtxtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPassKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jbttEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbttSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblPassqord)
                                    .addComponent(jlblUsuario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(jtxtPass))))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblEntradaUsuario)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlblEntradaUsuario)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblUsuario)
                    .addComponent(jtxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPassqord)
                    .addComponent(jtxtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbttEntrar)
                    .addComponent(jbttSalir))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbttEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttEntrarActionPerformed
        logIn();
    }//GEN-LAST:event_jbttEntrarActionPerformed
    private void logIn(){
        UserDto userDto = new UserDto();
        UserDao userDao = null;
                
        try {
            userDao = new UserDao();
        } catch (Exception ex) {
            Logger.getLogger(frm_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            if(userDao.LogIn(jtxtUser.getText(), jtxtPass.getText())){
               // JOptionPane.showMessageDialog(this, "Entró...");
                frm_Principal principal = new frm_Principal();
                principal.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
                principal.setPreferredSize(new Dimension(400, 400));
                principal.pack();
                principal.setVisible(true);
                this.dispose();
                ;
            }else{
                JOptionPane.showMessageDialog(this, "Error...");
            }
// TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(frm_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jbttSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbttSalirActionPerformed

    private void jtxtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPassKeyReleased
        if(evt.getKeyCode()==10){
            logIn();
        }
    }//GEN-LAST:event_jtxtPassKeyReleased

    private void jtxtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtUserKeyReleased
        if(evt.getKeyCode()==10){
            logIn();
        }
    }//GEN-LAST:event_jtxtUserKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbttEntrar;
    private javax.swing.JButton jbttSalir;
    private javax.swing.JLabel jlblEntradaUsuario;
    private javax.swing.JLabel jlblPassqord;
    private javax.swing.JLabel jlblUsuario;
    private javax.swing.JPasswordField jtxtPass;
    private javax.swing.JTextField jtxtUser;
    // End of variables declaration//GEN-END:variables
}
