/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uasd.insurance.vistas.principal;

import com.uasd.insurance.utilitario.ReportGenerator;
import com.uasd.insurance.vistas.mantenimientos.frm_Afiliado;
import com.uasd.insurance.vistas.mantenimientos.frm_Analisis;
import com.uasd.insurance.vistas.mantenimientos.frm_Institucion;
import com.uasd.insurance.vistas.mantenimientos.frm_Ocupacion;
import com.uasd.insurance.vistas.mantenimientos.frm_OrigenParentezco;
import com.uasd.insurance.vistas.mantenimientos.frm_Prestadores;
import com.uasd.insurance.vistas.mantenimientos.frm_TipoAfiliacion;
import com.uasd.insurance.vistas.mantenimientos.frm_TipoCobertura;
import com.uasd.insurance.vistas.mantenimientos.frm_TipoPago;
import com.uasd.insurance.vistas.mantenimientos.frm_TipoParentezco;
import com.uasd.insurance.vistas.mantenimientos.frm_TipoPlan;
import com.uasd.insurance.vistas.mantenimientos.frm_TipoPss;
import com.uasd.insurance.vistas.mantenimientos.frm_TipoSangre;
import com.uasd.insurance.vistas.mantenimientos.frm_TipoServicio;
import com.uasd.insurance.vistas.transacciones.frm_Pago;
import com.uasd.insurance.vistas.transacciones.frm_Reclamacion;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;

/**
 *
 * @author Sulenni
 */
public class frm_Principal extends javax.swing.JFrame {

    /**
     * Creates new form frm_Principal
     */
    public frm_Principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/blue.png"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMnPrestador = new javax.swing.JMenuItem();
        jMnPrestador1 = new javax.swing.JMenuItem();
        jMnPrestador2 = new javax.swing.JMenuItem();
        jMnPrestador3 = new javax.swing.JMenuItem();
        jMnPrestador4 = new javax.swing.JMenuItem();
        jMnPrestador5 = new javax.swing.JMenuItem();
        jMnPrestador6 = new javax.swing.JMenuItem();
        jMnPrestador7 = new javax.swing.JMenuItem();
        jMnPrestador8 = new javax.swing.JMenuItem();
        jMnPrestador9 = new javax.swing.JMenuItem();
        jMnPrestador10 = new javax.swing.JMenuItem();
        jMnPrestador11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemPagos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(51, 153, 255));
        jMenuBar1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N

        jMenu1.setText("MANTENIMIENTOS");
        jMenu1.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMenuItem3.setText("Análisis");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMenuItem1.setText("Afiliado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMnPrestador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMnPrestador.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMnPrestador.setText("Prestador");
        jMnPrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnPrestadorActionPerformed(evt);
            }
        });
        jMenu1.add(jMnPrestador);

        jMnPrestador1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jMnPrestador1.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMnPrestador1.setText("Institución");
        jMnPrestador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnPrestador1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMnPrestador1);

        jMnPrestador2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMnPrestador2.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMnPrestador2.setText("Ocupación");
        jMnPrestador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnPrestador2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMnPrestador2);

        jMnPrestador3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMnPrestador3.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMnPrestador3.setText("Origen parentezco");
        jMnPrestador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnPrestador3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMnPrestador3);

        jMnPrestador4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMnPrestador4.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMnPrestador4.setText("Tipo afiliación");
        jMnPrestador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnPrestador4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMnPrestador4);

        jMnPrestador5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMnPrestador5.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMnPrestador5.setText("Tipo cobertura");
        jMnPrestador5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnPrestador5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMnPrestador5);

        jMnPrestador6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMnPrestador6.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMnPrestador6.setText("Tipo pago");
        jMnPrestador6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnPrestador6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMnPrestador6);

        jMnPrestador7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        jMnPrestador7.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMnPrestador7.setText("Tipo parentezco");
        jMnPrestador7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnPrestador7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMnPrestador7);

        jMnPrestador8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        jMnPrestador8.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMnPrestador8.setText("Tipo plan");
        jMnPrestador8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnPrestador8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMnPrestador8);

        jMnPrestador9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        jMnPrestador9.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMnPrestador9.setText("Tipo PSS");
        jMnPrestador9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnPrestador9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMnPrestador9);

        jMnPrestador10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.CTRL_MASK));
        jMnPrestador10.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMnPrestador10.setText("Tipo Sangre");
        jMnPrestador10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnPrestador10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMnPrestador10);

        jMnPrestador11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.CTRL_MASK));
        jMnPrestador11.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMnPrestador11.setText("Tipo Servicio");
        jMnPrestador11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnPrestador11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMnPrestador11);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("TRANSACCIONES");
        jMenu2.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMenuItem2.setText("Reclamación");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItemPagos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemPagos.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMenuItemPagos.setText("Pagos");
        jMenuItemPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPagosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPagos);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("REPORTES");
        jMenu5.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMenuItem4.setText("Análisis");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMenuItem5.setText("Afiliados");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMenuItem6.setText("Prestadores");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jMenuItem7.setText("Prestadores 2");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frm_Afiliado afiliado = null;
        try {
            afiliado = new frm_Afiliado();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(afiliado);
        afiliado.setVisible(true);
        
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = afiliado.getSize();
        afiliado.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        afiliado.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    public void agregarFormulario(JInternalFrame frm){
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = frm.getSize();
        
        
        jDesktopPane1.add(frm);
        frm.setVisible(true);
        
        frm.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
    }
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        frm_Reclamacion reclamacion = null;
        try {
            reclamacion = new frm_Reclamacion(this);
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(reclamacion);
        reclamacion.setVisible(true);
        
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = reclamacion.getSize();
        reclamacion.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        reclamacion.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        
        frm_Analisis analisis = null;
        try {
            analisis = new frm_Analisis();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(analisis);
        analisis.setVisible(true);
        
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = analisis.getSize();
        analisis.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        analisis.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ReportGenerator.allAnalisis();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ReportGenerator.allAfiliado();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ReportGenerator.allPrestadores();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ReportGenerator.allPrestadores2();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMnPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnPrestadorActionPerformed
        frm_Prestadores frmPrestador = new frm_Prestadores(this);
        agregarFormulario(frmPrestador);
    }//GEN-LAST:event_jMnPrestadorActionPerformed

    private void jMenuItemPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPagosActionPerformed
        frm_Pago pago = null;
        try {
            pago = new frm_Pago();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(pago);
        pago.setVisible(true);
        
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = pago.getSize();
        pago.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        pago.show();
    }//GEN-LAST:event_jMenuItemPagosActionPerformed

    private void jMnPrestador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnPrestador1ActionPerformed
        frm_Institucion frmInstitucion = null;
        try {
            frmInstitucion = new frm_Institucion();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        agregarFormulario(frmInstitucion);
    }//GEN-LAST:event_jMnPrestador1ActionPerformed

    private void jMnPrestador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnPrestador2ActionPerformed
        frm_Ocupacion frmOcupacion = null;
        try {
            frmOcupacion = new frm_Ocupacion();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        agregarFormulario(frmOcupacion);
    }//GEN-LAST:event_jMnPrestador2ActionPerformed

    private void jMnPrestador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnPrestador3ActionPerformed
        frm_OrigenParentezco frmOrigenParentezco = null;
        try {
            frmOrigenParentezco = new frm_OrigenParentezco();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        agregarFormulario(frmOrigenParentezco);
    }//GEN-LAST:event_jMnPrestador3ActionPerformed

    private void jMnPrestador4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnPrestador4ActionPerformed
        frm_TipoAfiliacion frmTipoAfiliacion = null;
        try {
            frmTipoAfiliacion = new frm_TipoAfiliacion();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        agregarFormulario(frmTipoAfiliacion);
    }//GEN-LAST:event_jMnPrestador4ActionPerformed

    private void jMnPrestador5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnPrestador5ActionPerformed
        frm_TipoCobertura frmTipoCobertura = null;
        try {
            frmTipoCobertura = new frm_TipoCobertura();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        agregarFormulario(frmTipoCobertura);
    }//GEN-LAST:event_jMnPrestador5ActionPerformed

    private void jMnPrestador6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnPrestador6ActionPerformed
        frm_TipoPago frmTipoPago = null;
        try {
            frmTipoPago = new frm_TipoPago();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        agregarFormulario(frmTipoPago);
    }//GEN-LAST:event_jMnPrestador6ActionPerformed

    private void jMnPrestador7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnPrestador7ActionPerformed
        frm_TipoParentezco frmTipoParentezco = null;
        try {
            frmTipoParentezco = new frm_TipoParentezco();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        agregarFormulario(frmTipoParentezco);
    }//GEN-LAST:event_jMnPrestador7ActionPerformed

    private void jMnPrestador8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnPrestador8ActionPerformed
        frm_TipoPlan frmTipoPlan = null;
        try {
            frmTipoPlan = new frm_TipoPlan();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        agregarFormulario(frmTipoPlan);
    }//GEN-LAST:event_jMnPrestador8ActionPerformed

    private void jMnPrestador9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnPrestador9ActionPerformed
        frm_TipoPss frmTipoPss = null;
        try {
            frmTipoPss = new frm_TipoPss();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        agregarFormulario(frmTipoPss);
    }//GEN-LAST:event_jMnPrestador9ActionPerformed

    private void jMnPrestador10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnPrestador10ActionPerformed
        frm_TipoSangre frmTipoSangre = null;
        try {
            frmTipoSangre = new frm_TipoSangre();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        agregarFormulario(frmTipoSangre);
    }//GEN-LAST:event_jMnPrestador10ActionPerformed

    private void jMnPrestador11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnPrestador11ActionPerformed
        frm_TipoServicio frmTipoServicio = null;
        try {
            frmTipoServicio = new frm_TipoServicio();
        } catch (Exception ex) {
            Logger.getLogger(frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        agregarFormulario(frmTipoServicio);
    }//GEN-LAST:event_jMnPrestador11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemPagos;
    private javax.swing.JMenuItem jMnPrestador;
    private javax.swing.JMenuItem jMnPrestador1;
    private javax.swing.JMenuItem jMnPrestador10;
    private javax.swing.JMenuItem jMnPrestador11;
    private javax.swing.JMenuItem jMnPrestador2;
    private javax.swing.JMenuItem jMnPrestador3;
    private javax.swing.JMenuItem jMnPrestador4;
    private javax.swing.JMenuItem jMnPrestador5;
    private javax.swing.JMenuItem jMnPrestador6;
    private javax.swing.JMenuItem jMnPrestador7;
    private javax.swing.JMenuItem jMnPrestador8;
    private javax.swing.JMenuItem jMnPrestador9;
    // End of variables declaration//GEN-END:variables
}
